### ISSUE TITLE
format deletes alt in pardef

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-dixtools#7] opened 2023-01-05 13:33 UTC
I do:
`~/apertium/apertium-dixtools/apertium-dixtools format -alignMonodix apertium-oci.oci.metadix new.metadix`

Then:
`  <pardef n="S__cantar" alt="oci@aran">
`
becomes
`<pardef n="S__cantar">
`

**Comment by TinoDidriksen** [comment] 2023-10-18 22:47
Duplicate of https://github.com/apertium/apertium-dixtools/issues/1

**Closed by TinoDidriksen** 2023-10-18 22:47 UTC
Labels: duplicate
